# Generated by Django 4.0.4 on 2022-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='UniqCode',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
