# Generated by Django 4.0.4 on 2022-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_examdetails_uniqcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='UniqCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='totalq',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='qno',
            field=models.CharField(max_length=10),
        ),
    ]
